POST http://localhost:3333/videos
# dizer o tipo de conteudo que vc está mandando
Content-Type: application/json

{
    "titulo": "Video 01",
    "info": "Esse é o Primeiro Video",
    "tempo": 180
}

# os 3 jogo da velha, ta separando as requests

###

GET http://localhost:3333/videos
