POST http://localhost:3333/videos
# dizer o tipo de conteudo que vc está mandando
Content-Type: application/json

{
    "titulo": "video node",
    "info": "Esse é o Primeiro Video",
    "tempo": 180
}

# os 3 jogo da velha, ta separando as requests

###

GET http://localhost:3333/videos?search=node

###

# Lembra q aki vc tem q colocar o ID que vc quer q mude
PUT http://localhost:3333/videos
# dizer o tipo de conteudo que vc está mandando
Content-Type: application/json

{
    "titulo": "Video 02",
    "info": "Esse é o Primeiro Video",
    "tempo": 180
}

###
# aki é a msm coisa, coloca o id q vc quer deletar
DELETE  http://localhost:3333/videos